{% set name = "exhale" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/exhale-{{ version }}.tar.gz
  sha256: 752a96d0a59456511d933311d4a81f642cd668296eacd2561905727d5ed6b0d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - breathe >=4.32.0
    - docutils >=0.12
    - lxml
    - python >={{ python_min }}
    - six
    - sphinx >=3.0,<5

test:
  imports:
    - exhale
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/svenevs/exhale
  summary: Automatic C++ library API documentation generator using Doxygen, Sphinx, and
  dev_url: https://github.com/svenevs/exhale
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillon-cullinan
    - mariusvniekerk
    - rigzba21
